name: BuildAndTest
on: [pull_request]

env:
  DOCKER_IMAGE: uwhackweek/snowex

jobs:
  build-image-without-pushing:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Build Only
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: 'true'
        IMAGE_NAME: ${{ env.DOCKER_IMAGE }}
        #MYBINDERORG_TAG: ${{ github.event.pull_request.head.ref }} #clutters output log

    - name: Report Image Size and Conda Packages
      run: |
        docker images
        docker run ${{ env.DOCKER_IMAGE }}:latest conda list --export
        docker run ${{ env.DOCKER_IMAGE }}:latest conda list --explicit > conda-linux-64.lock

    - name: Save conda lockfile
      uses: actions/upload-artifact@v2
      with:
        name: lockfile
        path: conda-linux-64.lock
